module.exports = {
  apps: [
    {
      name: 'ths-thm-api',
      script: 'dist/main.js',
      cwd: './apps/api',
      instances: 'max',
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        APP_PORT: 3001,
      },
      error_file: '../../logs/api-err.log',
      out_file: '../../logs/api-out.log',
      log_file: '../../logs/api-combined.log',
      time: true,
      merge_logs: true,
      max_memory_restart: '1G',
      node_args: '--max-old-space-size=1024',
      watch: false,
      ignore_watch: ['node_modules', 'logs', 'dist'],
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: '30s',
    },
    {
      name: 'ths-thm-web',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 3000',
      cwd: './apps/web',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
      },
      error_file: '../../logs/web-err.log',
      out_file: '../../logs/web-out.log',
      log_file: '../../logs/web-combined.log',
      time: true,
      merge_logs: true,
      max_memory_restart: '512M',
      node_args: '--max-old-space-size=512',
      watch: false,
      ignore_watch: ['node_modules', 'logs', '.next'],
      restart_delay: 4000,
      max_restarts: 10,
      min_uptime: '30s',
    },
  ],
  deploy: {
    production: {
      user: 'deploy',
      host: 'your-production-server.com',
      ref: 'origin/main',
      repo: 'git@github.com:your-org/ths-thm-system.git',
      path: '/var/www/ths-thm-system',
      'pre-deploy-local': '',
      'post-deploy': 'pnpm install && pnpm build && pnpm db:deploy && pm2 reload ecosystem.config.js --env production',
      'pre-setup': '',
    },
  },
};