packages:
  - 'apps/*'
  - 'packages/*'

nodeLinker: hoisted

overrides:
  react: 18.2.0
  react-dom: 18.2.0
  '@types/react': 18.2.0

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  'msgpackr-extract': true
  'prisma': true
  'protobufjs': true
  'sharp': true
  'unrs-resolver': true
