name: ths_thm_flutter
description: Aplikasi Flutter mandiri untuk THS-THM.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  intl: ^0.19.0

flutter:
  uses-material-design: true
